import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-mono max-w-7xl mx-auto">
        <ClerkProvider>
          <Header />
          <div className="flex  min-h-screen gap-2">
            <div>
              <Sidebar />
            </div>

            <div className="flex-1 bg-cyan-100 shadow-lg shadow-cyan-500/50  m-4 overflow-y-auto scrollbar-hidden rounded-lg">
              {children}
            </div>
          </div>
        </ClerkProvider>
      </body>
    </html>
  );
}
